[package]
name = "argus_common"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.33.0", features = ["serde", "serde-serialize"] }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.10.0", features = ["serde", "v4"] }
